import json,pathlib,hashlib,datetime
p=pathlib.Path('data/sources');manifest=json.loads((p/'manifest.json').read_text())
titles={'axis-product':('Priority debit current product page','Axis Bank','Features and benefits: 2 domestic visits per quarter','current'),'icici-wealth':('ICICI Wealth Management World debit FAQ','ICICI Bank','Lounge FAQ: account scope, alternatives, salary and family banking','current'),'icici-lounges':('ICICI debit lounge directory','ICICI Bank','Downloaded directory; scanned pages not yet curated','directory'),'icici-terms':('ICICI debit card general terms','ICICI Bank','General debit card terms; not a replacement for programme-specific FAQ','current'),'hdfc-regalia-gold-2026':('Regalia Gold lounge terms • July 2026','HDFC Bank','Page 1: new terms effective 01-07-2026','current'),'hdfc-check-spend':('Regalia Gold NetBanking eligibility guide','HDFC Bank','Page 1: ₹60,000 in a calendar quarter, next-quarter access','current'),'hdfc-legacy':('Regalia Gold travel article • April 2024','HDFC Bank','Historical article: 12 annual India visits','historical'),'axis-priority-2026':('Priority debit revisions • September 2026','Axis Bank','Page 1: lounge programme and excluded categories','current'),'axis-lounges':('Axis debit lounge directory','Axis Bank','Table 3, page 4: Priority Debit Card / RuPay Platinum NRO','directory')}
sources=[dict(id=m['id'],title=titles[m['id']][0],url=m['url'],publisher=titles[m['id']][1],locator=titles[m['id']][2],retrievedAt=m['retrievedAt'],sha256=m['sha256'],role=titles[m['id']][3]) for m in manifest if 'sha256' in m]
def amount(field,minimum,label):return dict(kind='amount',field=field,min=minimum,label=label)
base=dict(_type='loungePolicy',reviewedAt='2026-10-03',reviewBy='2026-10-31',openedOnOrAfter=None,programRequired=False,releaseDay=1,conflictIds=[],notes=[])
icici=dict(base,card='icici-wealth-world',issuer='ICICI Bank',validFrom='2025-08-01',window='previous-quarter',releaseDay=5,quota=2,waiver='none',programRequired=True,sourceIds=['icici-wealth'],accessMethod='Present the exact eligible card at a bank-listed domestic airport lounge; bank validation and lounge admission still apply.',spendNotes='Use eligible debit card spending from the full preceding calendar quarter. Access starts on the fifth after quarter end.')
spend=amount('eligibleSpend',10000,'Previous-quarter debit spend')
policies=[dict(icici,_id='policy-icici-savings',title='Wealth World • individual savings',accountTypes=['savings'],openedOnOrAfter='2025-08-01',alternatives=[spend,amount('balance',1000000,'Deposits + account balance'),amount('relationship',5000000,'Total programme relationship')]),dict(icici,_id='policy-icici-salary',title='Wealth World • salary account',accountTypes=['salary'],alternatives=[spend]),dict(icici,_id='policy-icici-family',title='Wealth World • family savings',accountTypes=['family-savings'],alternatives=[spend,dict(kind='family',label='1.5× programme eligibility at family ID')]),dict(base,_id='policy-hdfc-regalia-gold-202607',card='hdfc-regalia-gold',issuer='HDFC Bank',title='Regalia Gold • India lounge benefit',validFrom='2026-07-01',accountTypes=['savings','salary','family-savings','unknown'],window='previous-quarter',quota=3,waiver='last-month-next-quarter-conditional',alternatives=[amount('eligibleSpend',60000,'Previous-quarter settled retail spend')],sourceIds=['hdfc-regalia-gold-2026','hdfc-check-spend'],conflictIds=['conflict-hdfc-annual-quarterly'],accessMethod='Swipe the Regalia Gold card at a listed lounge. A ₹2 validation charge is reversed. No lounge vouchers are issued under these terms.',spendNotes='Only settled retail debit transactions count. EMI transactions do not count. The settlement date determines the qualifying quarter.',notes=['New cards opened in the last month of the prior quarter may be exempted; verify entitlement with the bank.']),dict(base,_id='policy-axis-priority-202609',card='axis-priority',issuer='Axis Bank',title='Priority debit • revised spend requirement',validFrom='2026-09-01',accountTypes=['savings','salary','family-savings','unknown'],window='previous-three-months',releaseDay=2,quota=2,waiver='issue-month-plus-three',alternatives=[amount('eligibleSpend',10000,'Billed debit spend in previous three calendar months')],sourceIds=['axis-priority-2026','axis-product','axis-lounges'],accessMethod='Use the eligible Priority debit card at a lounge listed in Table 3. Entry is subject to bank validation and operator conditions.',spendNotes='From 1 October 2026, exclude UPI, wallet reloads, credit card bill payments and cash withdrawals. Use billed transactions in the previous three calendar months. Eligibility updates on the 2nd of each month; the 1st carries the previous month’s status.')]
# Three airports, precise terminal and flight section. No inference from another card table.
rows=[('DEL','T1','domestic','Encalm Lounge',22),('DEL','T3','domestic','Encalm Lounge',23),('DEL','T3','international','Encalm Lounge',24),('BLR','T1','domestic','080 Domestic Lounge',3),('BLR','T2','international','080 International Lounge',4),('BOM','T1B','domestic','Adani Lounge',18),('BOM','T2','domestic','Travel Club T2',19),('BOM','T1C','domestic','Travel Club T1',20),('BOM','T2','international','Adani East Lounge',21)]
lounges=[dict(_id=f'lounge-axis-{i}',_type='lounge',card='axis-priority',airport=a,terminal=t,flightType=f,name=n,sourceId='axis-lounges',locator=f'Table 3, page 4, row {i}') for a,t,f,n,i in rows]
conflicts=[dict(_id='conflict-hdfc-annual-quarterly',_type='policyConflict',card='hdfc-regalia-gold',title='Annual marketing claim vs dated quarterly eligibility',sourceIds=['hdfc-legacy','hdfc-regalia-gold-2026'],status='resolved',decision='Use the detailed dated July 2026 lounge terms for trips on or after 1 July 2026. The 2024 article does not establish unconditional access today. The annual total alone omits preceding-quarter spend, per-quarter quota, EMI exclusions and issuance exception. This decision is an editorial interpretation, not bank confirmation.',decidedAt='2026-10-03')]
pathlib.Path('data/corpus.json').write_text(json.dumps(dict(sources=sources,policies=policies,lounges=lounges,conflicts=conflicts),indent=2))
